BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PichuBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PolitoedBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw WuDukBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw TyrogueBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw HitmontopBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw HappinyBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw KangaskidBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw ElekidBitmasks
	dw ElectabuzzBitmasks
	dw MagbyBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw MoobyBitmasks
	dw TaurosBitmasks
	dw MiltankBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw NessiBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw NatuBitmasks
	dw IatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw AmbipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw WynautBitmasks
	dw WobbuffetBitmasks
	dw OkapakoBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw DuserpentBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw RinrinBitmasks
	dw BellunaBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw DetoqwilBitmasks
	dw ShuckleBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantykeBitmasks
	dw MantineBitmasks
	dw SkarchicBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw SmeargleBitmasks
	dw HeracrossBitmasks
	dw UnownBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw ChimereonBitmasks
	dw Bulbasaur_CloneBitmasks
	dw Ivysaur_CloneBitmasks
	dw Venusaur_CloneBitmasks
	dw Charmander_CloneBitmasks
	dw Charmeleon_CloneBitmasks
	dw Charizard_CloneBitmasks
	dw Squirtle_CloneBitmasks
	dw Wartortle_CloneBitmasks
	dw Blastoise_CloneBitmasks
	dw Ekans_DarkBitmasks
	dw Arbok_DarkBitmasks
	dw Pichu_SpikyBitmasks
	dw Pikachu_CloneBitmasks
	dw Raichu_CloneBitmasks
	dw Raichu_AlolanBitmasks
	dw Sandshrew_AlolanBitmasks
	dw Sandslash_AlolanBitmasks
	dw Vulpix_AlolanBitmasks
	dw Ninetales_AlolanBitmasks
	dw Growlithe_HisuianBitmasks
	dw Arcanine_HisuianBitmasks
	dw Voltorb_HisuianBitmasks
	dw Electrode_HisuianBitmasks
	dw Marowak_AlolanBitmasks
	dw Typhlosion_HisuianBitmasks
	dw Articuno_GalarianBitmasks
	dw Zapdos_GalarianBitmasks
	dw Moltres_GalarianBitmasks
	dw Arbok_KantoBitmasks
	dw Arbok_SeviiBitmasks
	dw Wooper_PaldeanBitmasks
	dw ClodsireBitmasks
	dw StarlyBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
