FramesPointers:
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PichuFrames
	dba PikachuFrames
	dba RaichuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba CrobatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba PolitoedFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba SlowkingFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba FarfetchDFrames
	dba WuDukFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba SteelixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba TyrogueFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba HitmontopFrames
	dba LickitungFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba BlisseyFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba KingdraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba ScytherFrames
	dba ScizorFrames
	dba ElekidFrames
	dba ElectabuzzFrames
	dba MagbyFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MiltankFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba LeafeonFrames
	dba GlaceonFrames
	dba PorygonFrames
	dba Porygon2Frames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba AmbipomFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba YanmegaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba MurkrowFrames
	dba HonchkrowFrames
	dba MisdreavusFrames
	dba MismagiusFrames
	dba WobbuffetFrames
	dba GirafarigFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba DuserpentFrames
	dba GligarFrames
	dba GliscorFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba ShuckleFrames
	dba SneaselFrames
	dba WeavileFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba DelibirdFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba StantlerFrames
	dba SmeargleFrames
	dba HeracrossFrames
	dba UnownFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba Vulpix_AlolanFrames
	dba Ninetales_AlolanFrames
