AnimationIdlePointers:
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PichuAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw CrobatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw BellossomAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw AnnihilapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw PolitoedAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw SlowkingAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw WuDukAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw SteelixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw HitmontopAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw HappinyAnimationIdle
	dw ChanseyAnimationIdle
	dw BlisseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskidAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw KingdraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw ElekidAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagbyAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw MoobyAnimationIdle
	dw TaurosAnimationIdle
	dw MiltankAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw NessiAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodonAnimationIdle
	dw AerodactylAnimationIdle
	dw MunchlaxAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw NatuAnimationIdle
	dw IatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw BonslyAnimationIdle
	dw SudowoodoAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw AmbipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw MurkrowAnimationIdle
	dw HonchkrowAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw WynautAnimationIdle
	dw WobbuffetAnimationIdle
	dw OkapakoAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw DuserpentAnimationIdle
	dw GligarAnimationIdle
	dw GliscorAnimationIdle
	dw RinrinAnimationIdle
	dw BellunaAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw DetoqwilAnimationIdle
	dw ShuckleAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantykeAnimationIdle
	dw MantineAnimationIdle
	dw SkarchicAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw StantlerAnimationIdle
	dw WyrdeerAnimationIdle
	dw SmeargleAnimationIdle
	dw HeracrossAnimationIdle
	dw UnownAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw ChimereonAnimationIdle
	dw Bulbasaur_CloneAnimationIdle
	dw Ivysaur_CloneAnimationIdle
	dw Venusaur_CloneAnimationIdle
	dw Charmander_CloneAnimationIdle
	dw Charmeleon_CloneAnimationIdle
	dw Charizard_CloneAnimationIdle
	dw Squirtle_CloneAnimationIdle
	dw Wartortle_CloneAnimationIdle
	dw Blastoise_CloneAnimationIdle
	dw Ekans_DarkAnimationIdle
	dw Arbok_DarkAnimationIdle
	dw Pichu_SpikyAnimationIdle
	dw Pikachu_CloneAnimationIdle
	dw Raichu_CloneAnimationIdle
	dw Raichu_AlolanAnimationIdle
	dw Sandshrew_AlolanAnimationIdle
	dw Sandslash_AlolanAnimationIdle
	dw Vulpix_AlolanAnimationIdle
	dw Ninetales_AlolanAnimationIdle
	dw Growlithe_HisuianAnimationIdle
	dw Arcanine_HisuianAnimationIdle
	dw Voltorb_HisuianAnimationIdle
	dw Electrode_HisuianAnimationIdle
	dw Marowak_AlolanAnimationIdle
	dw Typhlosion_HisuianAnimationIdle
	dw Articuno_GalarianAnimationIdle
	dw Zapdos_GalarianAnimationIdle
	dw Moltres_GalarianAnimationIdle
	dw Arbok_KantoAnimationIdle
	dw Arbok_SeviiAnimationIdle
	dw Wooper_PaldeanAnimationIdle
	dw ClodsireAnimationIdle
	dw StarlyAnimationIdle
	dw StaraviaAnimationIdle
	dw StaraptorAnimationIdle
	dw SuicudraxAnimationIdle
	dw RaiensuiAnimationIdle
	dw Omastar_FossilAnimationIdle
	dw Kabutops_FossilAnimationIdle
	dw Aerodactyl_FossilAnimationIdle
	dw MissingnoAnimationIdle
	dw Charizard_MAnimationIdle
