UnownFramesPointers:
	dba UnownAFrames
	dba UnownBFrames
	dba UnownCFrames
	dba UnownDFrames
	dba UnownEFrames
	dba UnownFFrames
	dba UnownGFrames
	dba UnownHFrames
	dba UnownIFrames
	dba UnownJFrames
	dba UnownKFrames
	dba UnownLFrames
	dba UnownMFrames
	dba UnownNFrames
	dba UnownOFrames
	dba UnownPFrames
	dba UnownQFrames
	dba UnownRFrames
	dba UnownSFrames
	dba UnownTFrames
	dba UnownUFrames
	dba UnownVFrames
	dba UnownWFrames
	dba UnownXFrames
	dba UnownYFrames
	dba UnownZFrames
